### ISSUE TITLE
no info box in cat flatmap

### ISSUE THREAD

**Issue by keeran97** [AnatomicMaps/flatmap-maker#21]
when generating the cat flatmap, there is no pop-up information box for each feature (that typically appears when you hover over a feature). this indicates the features arent being registered. the annotations in the JSON files are set up as the rat flatmap was. however, I notice that this only occurs when using boxy. if I annotate the features in AI and export it, things are working.

as an example, I have annotated the lung with `digestive_2-1` in AI. when generating the map with this file, you can see the registration of information on the flatmap. however, making these edits with boxy does not do the same. the AI edited file is too big to upload here. so all the files are in the `keerans_changes` branch of the cat flatmap repo.

i am wondering if the SVG can be annotated the same way in boxy as it is in AI. i.e. using `.id(____)`?

**Comment by keeran97** [comment]
im now getting information registered to features, as seen in the attached image. I'm thinking its because I've started generating the map with `--clean` because there are no other changes that I've made to the SVG. the most recent SVG file has been pushed to git. 
![image](https://user-images.githubusercontent.com/85910337/197079614-2e8b1f85-9079-47d8-81a7-8382787e3ecc.png)

**Comment by dbrnz** [comment]
`--clean` wouldn't have changed things. I suspect it's more to do with either using an old version of mapmaker or if not, to do with caching in the browser.

**Comment by dbrnz** [comment]
> i am wondering if the SVG can be annotated the same way in boxy as it is in AI. i.e. using .id()

Only if you want to manually encode clear text into AI's format for IDs (i.e. starting with `_x2E_id`).

**Comment by keeran97** [comment]
i had not updated mapmaker within the two hours of my initial first two comments. and I'm not even sure if there were updates to pull down anyway? but the only difference in that timeframe was that I was continuing to annotate features (using the `.id(_______)` format, and that I was using `--clean` to generate the map. so seems like things have somehow fixed themselves!

> Only if you want to manually encode clear text into AI's format for IDs (i.e. starting with _x2E_id).
but I assume this is something we don't want/need to do? using the `.id(____X-X)`  format seems to be working so far so I will continue using that (until something stops working I guess)
