### ISSUE TITLE
Incorrectly flagged errors in FC map

### ISSUE THREAD

**Issue by keeran97** [AnatomicMaps/flatmap-maker#41]
Noting down our discussion from Friday 24/03 meeting. The below cases are paths (from the FC) incorrectly flagged in yellow with errors.

The path in the ventricular ICG is meant to connect between different points, as per Ardell model (path 10v I think). Therefore the error is ignoreable as the path is correct.
`2023-03-24 14:26:59,789 ERROR: Connection type doesn't match connector's: intracardiac != para`
![image](https://user-images.githubusercontent.com/85910337/227412332-4517ac8c-c7cb-4c9a-803f-6a30a57932d4.png)

The set of paths in the cardiorespiratory ppt highlighted yellow are because they are flagged as unconnected. But after investigation and attempting to fix it nothing seems to resolve these issues. And as per our discussion this is a mapmaker issue. However, let me know if you pick up on something I've missed. 
![image](https://user-images.githubusercontent.com/85910337/227412548-b21a43d9-d4a4-4e3c-a8a0-ef0c02631edf.png)

**Comment by dbrnz** [comment]
Noted! In future though please raise individual tickets for unrelated items...

**Comment by dbrnz** [comment]
Replaced by tickets #44 and #45.
