### ISSUE TITLE
Disconnected path caused by incorrect use of itertools.product pairs

### ISSUE THREAD

**Issue by napakalas** [AnatomicMaps/flatmap-maker#95]
Found some disconnections caused by the incorrect parameter used in itertools.product function
The first input node should be in a list.

![Screenshot 2024-10-11 at 10 38 56 AM](https://github.com/user-attachments/assets/6a77e365-dc35-4d20-981c-5f2c69bf2e85)

**Comment by dbrnz** [comment]
Closed by PR #96.
